"""
Closed-loop Decision Replay (Phase 5d / Modification 2).

Two trajectories over the same date window, both starting from the same
actual historical Day-1 starting inventory:

- "actual": what really happened historically -- a pure passthrough of
  `daily_sku_timeseries.csv`, no computation needed, since that's literally
  what's already recorded there.
- "optimizer": each day's price is recommended by the ESTIMATED demand
  model (the exact same `demand_model.recommend_price[_bayesian]` the
  Scenario Explorer uses -- never touches ground truth), the REALIZED
  outcome (units actually sold) is generated by the TRUE simulator demand
  equation via `realize_true_outcome` (the only function in this codebase
  allowed to read `true_price_elasticity`), and the next day's starting
  inventory is whatever the optimizer's own decision left behind -- not the
  next fixed historical row. That's what makes it a closed loop instead of
  a passive replay.

This is only possible because Nova Retail is a synthetic economy with a
known true model -- see the landing page / Decision Replay page copy for
why that gap matters and why the estimation work in Phases 2-3 exists.

Replenishment: the optimizer trajectory's inventory gets the same absolute
top-up the real store network actually received each day (back-computed
from the actual trajectory's own day-over-day inventory), since restocking
is a supply-chain decision made independently of which pricing policy is
being tested -- not a random draw this module invents.
"""

from __future__ import annotations

from dataclasses import dataclass

import pandas as pd

from demand_model import build_demand_context, recommend_price, recommend_price_bayesian
from optimization import constant_elasticity_units


def realize_true_outcome(
    candidate_price: float,
    actual_price: float,
    demand_units_uncapped: float,
    true_price_elasticity: float,
    available_inventory: float,
) -> float:
    """
    The ONLY function in this codebase allowed to read true_price_elasticity.

    What the TRUE simulator model says would have happened at
    `candidate_price`, holding this day's other realized conditions
    (promotion, marketing, event, day-of-week, noise) fixed -- captured
    implicitly by anchoring at the day's own actual (price, uncapped
    demand) pair rather than needing those factors named explicitly, then
    capped by whatever inventory this trajectory actually has on hand.
    """
    uncapped_units = constant_elasticity_units(
        candidate_price, actual_price, demand_units_uncapped, true_price_elasticity
    )
    return float(min(uncapped_units, available_inventory))


@dataclass
class ReplayDay:
    date: pd.Timestamp
    actual_price: float
    actual_units: float
    actual_starting_inventory: float
    actual_ending_inventory: float
    actual_revenue: float
    actual_profit: float
    optimizer_price: float
    optimizer_units: float
    optimizer_starting_inventory: float
    optimizer_ending_inventory: float
    optimizer_revenue: float
    optimizer_profit: float
    optimizer_stockout: bool


def run_closed_loop_replay(
    sku_master: pd.DataFrame,
    daily: pd.DataFrame,
    sku: str,
    start_date,
    n_days: int,
    objective: str = "maximize_profit",
    elasticity_samples=None,
    risk_aversion: float = 0.3,
    min_margin: float | None = None,
    max_price_change_pct: float | None = None,
) -> list[ReplayDay]:
    """
    Step through `n_days` starting at `start_date` for `sku`, building both
    trajectories. Uses `recommend_price_bayesian` if `elasticity_samples` is
    given, else the point-estimate `recommend_price`.
    """
    start_date = pd.Timestamp(start_date)
    window_dates = pd.date_range(start_date, periods=n_days, freq="D")

    sku_daily = daily[daily["sku"] == sku].set_index("date").sort_index()
    missing = [d for d in window_dates if d not in sku_daily.index]
    if missing:
        raise ValueError(
            f"No data for {sku} on {missing[0].date()} -- replay window must stay within the dataset's date range."
        )

    sku_row = sku_master.loc[sku_master["sku"] == sku]
    if sku_row.empty:
        raise ValueError(f"Unknown sku {sku!r} -- not present in sku_master")
    cost = float(sku_row.iloc[0]["cost"])

    results: list[ReplayDay] = []
    optimizer_inventory = None  # set from actual Day-1 starting inventory below
    prev_actual_ending_inventory = None

    for date in window_dates:
        row = sku_daily.loc[date]

        actual_starting_inventory = float(row["starting_inventory"])
        actual_units = float(row["actual_units"])
        actual_ending_inventory = float(row["ending_inventory"])
        actual_price = float(row["actual_price"])

        if optimizer_inventory is None:
            # Day 1: same actual starting inventory as the historical trajectory.
            optimizer_inventory = actual_starting_inventory
        else:
            # The real simulator replenishes toward a *target level* (roughly
            # a fixed fraction of capacity), not by adding back whatever was
            # just consumed -- so a restock day tops the optimizer trajectory
            # up to that same target (only if it's currently below it; never
            # removes stock), and a non-restock day leaves it untouched. An
            # earlier version added the actual trajectory's absolute day-over-
            # day inventory delta instead, which -- since the optimizer
            # typically sells less than history under a protective price --
            # made its inventory drift upward without bound across the
            # window instead of tracking a sensible target.
            replenishment_occurred = actual_starting_inventory > prev_actual_ending_inventory + 1e-6
            if replenishment_occurred:
                optimizer_inventory = max(optimizer_inventory, actual_starting_inventory)

        context = build_demand_context(sku_master, daily, sku, date)

        if elasticity_samples is not None and len(elasticity_samples) > 0:
            result = recommend_price_bayesian(
                context,
                objective,
                elasticity_samples=elasticity_samples,
                risk_aversion=risk_aversion,
                inventory=optimizer_inventory,
                min_margin=min_margin,
                max_price_change_pct=max_price_change_pct,
            )
        else:
            result = recommend_price(
                context,
                objective,
                inventory=optimizer_inventory,
                min_margin=min_margin,
                max_price_change_pct=max_price_change_pct,
            )

        optimizer_price = result["recommended_price"]
        optimizer_units = realize_true_outcome(
            candidate_price=optimizer_price,
            actual_price=actual_price,
            demand_units_uncapped=float(row["demand_units_uncapped"]),
            true_price_elasticity=float(row["true_price_elasticity"]),
            available_inventory=optimizer_inventory,
        )
        optimizer_ending_inventory = optimizer_inventory - optimizer_units

        results.append(
            ReplayDay(
                date=date,
                actual_price=actual_price,
                actual_units=actual_units,
                actual_starting_inventory=actual_starting_inventory,
                actual_ending_inventory=actual_ending_inventory,
                actual_revenue=actual_price * actual_units,
                actual_profit=(actual_price - cost) * actual_units,
                optimizer_price=optimizer_price,
                optimizer_units=optimizer_units,
                optimizer_starting_inventory=optimizer_inventory,
                optimizer_ending_inventory=optimizer_ending_inventory,
                optimizer_revenue=optimizer_price * optimizer_units,
                optimizer_profit=(optimizer_price - cost) * optimizer_units,
                optimizer_stockout=optimizer_ending_inventory <= 0,
            )
        )

        prev_actual_ending_inventory = actual_ending_inventory
        optimizer_inventory = optimizer_ending_inventory

    return results


def replay_to_frame(days: list[ReplayDay]) -> pd.DataFrame:
    """Tabular form with cumulative profit/revenue for both trajectories, for charting."""
    df = pd.DataFrame([vars(d) for d in days])
    df["actual_cumulative_profit"] = df["actual_profit"].cumsum()
    df["optimizer_cumulative_profit"] = df["optimizer_profit"].cumsum()
    df["actual_cumulative_revenue"] = df["actual_revenue"].cumsum()
    df["optimizer_cumulative_revenue"] = df["optimizer_revenue"].cumsum()
    return df
